unit TVANIHLP;

interface

const

  hcCalculator           = 1400;
  hcCalendar             = 1300;
  hcCancelBtn            = 2115;
  hcConfAxis             = 7500;
  hcConfJoystick         = 7400;
  hcConfMcpu             = 7100;
  hcConfOptions          = 7600;
  hcConfRgb              = 7200;
  hcConfTrig             = 7300;
  hcEditDisplay          = 3400;
  hcEditGraphics         = 3500;
  hcEditPlot             = 3100;
  hcEditTaper            = 3300;
  hcEditTime             = 3200;
  hcFCChDirDBox          = 2131;
  hcFChangeDir           = 2103;
  hcFileDos              = 2800;
  hcFileNew              = 2200;
  hcFileOpen             = 2100;
  hcFileQuit             = 2900;
  hcFileSave             = 2300;
  hcFOFileOpenDBox       = 2111;
  hcFOFiles              = 2113;
  hcFOName               = 2112;
  hcFOOpenBtn            = 2114;
  hcFOpen                = 2101;
  hcGeneral              = 1100;
  hcJoystick             = 4500;
  hcMemory               = 1500;
  hcOpenBtn              = 2116;
  hcOveride              = 4400;
  hcPuzzle               = 1200;
  hcRunAlign             = 4300;
  hcRunGomo              = 4700;
  hcRunPlot              = 4100;
  hcRunReal              = 4200;
  hcRunStop              = 4600;
  hcSpecColor            = 6300;
  hcSpecLight            = 6200;
  hcSpecMcpu             = 6400;
  hcSpecRgb              = 6500;
  hcSpecTerm             = 6100;
  hcSpecTerm1            = 6110;
  hcSpecTerm2            = 6120;
  hcUtilAlign            = 5500;
  hcUtilAxis             = 5100;
  hcUtilSpeed            = 5300;
  hcUtilTrig             = 5400;
  hcUtilTrig1            = 5410;
  hcUtilUser             = 5200;
  hcViewer               = 2102;
  hcWCascade             = 9500;
  hcWClose               = 9800;
  hcWindows              = 9100;
  hcWNext                = 9600;
  hcWPrevious            = 9700;
  hcWSizeMove            = 9200;
  hcWTile                = 9400;
  hcWZoom                = 9300;

implementation

end.
