unit TVSEQHLP;

interface

const

  hcAsciiTable           = 6;
  hcCalculator           = 4;
  hcCalendar             = 5;
  hcCancelBtn            = 30;
  hcEdit                 = 14;
  hcEditCount            = 3900;
  hcEditDisplay          = 3400;
  hcEditGraphics         = 3500;
  hcEditPlot             = 3100;
  hcEditTaper            = 3300;
  hcEditTime             = 3200;
  hcFCChDirDBox          = 32;
  hcFile                 = 13;
  hcFileDos              = 2800;
  hcFileNew              = 2200;
  hcFileOpen             = 2100;
  hcFileQuit             = 2900;
  hcFileSave             = 2300;
  hcFind                 = 17;
  hcFOFileOpenDBox       = 26;
  hcFOFiles              = 28;
  hcFOName               = 27;
  hcFOOpenBtn            = 29;
  hcGeneral              = 1100;
  hcJoystick             = 4500;
  hcMemory               = 1500;
  hcNoContext            = 0;
  hcOCColorsDBox         = 34;
  hcOColors              = 23;
  hcOMMouseDBox          = 33;
  hcOMouse               = 22;
  hcOpenBtn              = 31;
  hcOptions              = 21;
  hcORestoreDesktop      = 25;
  hcOSaveDesktop         = 24;
  hcOveride              = 4400;
  hcPrevious             = 65318;
  hcPuzzle               = 3;
  hcReplace              = 18;
  hcRunAlign             = 4300;
  hcRunCam               = 4900;
  hcRunGomo              = 4700;
  hcRunPlot              = 4100;
  hcRunProj              = 4910;
  hcRunReal              = 4200;
  hcRunScript            = 4930;
  hcRunSeq               = 4920;
  hcRunStop              = 4600;
  hcSAbout               = 8;
  hcSAsciiTable          = 11;
  hcSCalculator          = 12;
  hcSCalendar            = 10;
  hcSearch               = 16;
  hcSearchAgain          = 19;
  hcShowClip             = 15;
  hcSpecColor            = 6300;
  hcSpecLight            = 6200;
  hcSpecMcpu             = 6400;
  hcSpecRgb              = 6500;
  hcSpecTerm             = 6100;
  hcSpecTerm1            = 6110;
  hcSpecTerm2            = 6120;
  hcSPuzzle              = 9;
  hcSystem               = 7;
  hcUtilAlign            = 5500;
  hcUtilAxis             = 5100;
  hcUtilSpeed            = 5300;
  hcUtilTrig             = 5400;
  hcUtilTrig1            = 5410;
  hcUtilUser             = 5200;
  hcViewer               = 2;
  hcWindows              = 20;

implementation

end.
